### ISSUE TITLE
Crash before title screen - Lambda error

### ISSUE THREAD

**Issue by BaccarWozat** [Ling-ALY/Jumpy-Boat-Fabric#1]
Description: Initializing game
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'jumpy-boats'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)

Log with all other mods: https://paste.ee/p/ysm22
Log without all other mods: https://paste.ee/p/MEW5f

Using: 22w16b, Fabric Loader 0.14.1, Fabric API 0.51.2, and JB 1.0.

**Comment by Alan-Yan-CanMeng** [comment]
I'm so sorry that I uploaded the old and error version. new version is available now.
